spring.application.name=discovery-service

server.port=8762

spring.cloud.discovery.enabled=true
eureka.client.service-url.defaultZone=${DISCOVERY_SERVICE_URL:http://localhost:8762/eureka}
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
